# Generated by Django 2.2.5 on 2019-10-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='User', max_length=150)),
                ('nombre', models.CharField(default='SOME STRING', max_length=150)),
                ('correo', models.EmailField(default='SOME STRING', max_length=150, unique=True)),
                ('entidad', models.CharField(default='SOME STRING', max_length=150)),
                ('password', models.CharField(default='defaultpass', max_length=150)),
                ('avatar', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
