# Generated by Django 2.2.5 on 2019-10-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquetas',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='entidad',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
        migrations.AddField(
            model_name='evento',
            name='etiqueta1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='etiqueta2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='etiqueta3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='Etiquetas',
        ),
    ]
