# Generated by Django 2.2.5 on 2019-10-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0004_regevento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='etiqueta1',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='etiqueta2',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='etiqueta3',
        ),
    ]
